import std.process;
import std.stdio;
import std.string;
import std.conv;
import std.array;
import std.algorithm;

struct NR
{
    string str; int nr;
}


version(linux)
{
    version(D_InlineAsm_X86_64)
    void genSyscall()
    {
        writeln("module syscalld.os.linux_x86_64;\n\n");
        writeln("// Automatically generated by util/gensyscall.d");
        write("//  kernel version: ");
        write(executeShell("uname -r").output);
        writeln("version(linux):\n");

        executeShell("printf '#include<sys/syscall.h>' | cpp -dM - | grep '__NR_'")
            .output.split("\n").map!(a => a.split(" "))
            .filter!(a => a.length >= 2 && a[2].isNumeric)
            .map!(a => NR(a[1], a[2].to!int))
            .array.sort!((a, b) => a.nr < b.nr)
            .each!(a => writeln("enum " ~ a.str[5 .. $].toUpper ~ " = " ~ a.nr.to!string ~ ";"));
    }
    version(D_InlineAsm_X86)
     void genSyscall()
    {
        writeln("module syscalld.os.linux_x86;\n\n");
        writeln("// Automatically generated by util/gensyscall.d");
        write("//  kernel version: ");
        write(executeShell("uname -r").output);
        writeln("version(linux):\n");

        executeShell("printf '#include<sys/syscall.h>' | cpp -dM - | grep '__NR_'")
            .output.split("\n").map!(a => a.split(" "))
            .filter!(a => a.length >= 2 && a[2].isNumeric)
            .map!(a => NR(a[1], a[2].to!int))
            .array.sort!((a, b) => a.nr < b.nr)
            .each!(a => writeln("enum " ~ a.str[5 .. $].toUpper ~ " = " ~ a.nr.to!string ~ ";"));
    }
}
version(OSX)
void genSyscall()
{
    writeln("module syscalld.os.osx_x86_64;\n");
    writeln("// Automatically generated by util/gensyscall.d");
    write("//  kernel version: ");
    write(executeShell("uname -r").output);
    writeln("version(OSX):\n");

    executeShell("printf '#include<sys/syscall.h>' | cpp -dM - | grep 'SYS_'")
        .output.split("\n").map!(a => a.split(" "))
        .filter!(a => a.length >= 2 && a[2].isNumeric)
        .map!(a => NR(a[1], a[2].to!int))
        .array.sort!((a, b) => a.nr < b.nr)
        .each!(a => writeln("enum " ~ a.str[4 .. $].toUpper ~ " = " ~ a.nr.to!string ~ ";"));
}
version(FreeBSD)
{
  void genSyscall()
  {
    writeln("module syscalld.os.freebsd_x86_64;\n");
    writeln("// Automatically generated by util/gensyscall.d");
    write("//  kernel version: ");
    write(executeShell("uname -r").output);
    writeln("version(FreeBSD):\n");

    executeShell("printf '#include<sys/syscall.h>' | cpp -dM - | grep 'SYS_'")
        .output.split("\n").map!(a => a.split(" "))
        .filter!(a => a.length >= 2 && a[2].isNumeric)
        .map!(a => NR(a[1], a[2].to!int))
        .array.sort!((a, b) => a.nr < b.nr)
        .each!(a => writeln("enum " ~ a.str[4 .. $].toUpper ~ " = " ~ a.nr.to!string ~ ";"));
  }
}

void main()
{
    genSyscall();
}
